######################## default configuration ####################
baseURL = "http://examplesite.org"
disableLanguages = ["Fr"]
title = "Educenter | hugo education template"
theme = "educenter-hugo"
# post pagination
paginate = "6"
summaryLength = "5"
theme = "educenter-hugo"
title = "Educenter | hugo education template"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "teacher"
name = "teacher"
[[menu.footer]]
URL = "event"
name = "event"
[[menu.footer]]
URL = "scholarship"
name = "scholarship"
[[menu.footer]]
URL = "research"
name = "research"
[[menu.main]]
URL = "contact"
name = "contact"
weight = 5
[params]
address = ""
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "admin@thinktoolsforchildren.org"
google_analitycs_id = ""
logo = "images/logo-white.png"
mobile = ""
social = []
top_header = false
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@educenter.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]

enable = false 
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "course"
url = "course"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "event"
  url = "event"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "scholarship"
  url = "scholarship"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"
  
[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 4
  
[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"



################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"
  
[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4
  
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"

[[Languages.fr.menu.footer]]
name = "event"
url = "event"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.fr.menu.footer]]
name = "research"
url = "research"
